INSERT INTO book (id, title, subtitle, authors, image) VALUES (1, 'Security as Code', 'DevSecOps Patterns with AWS', 'BK Sarthak Das, Virginia Chu', 'https://www.dbooks.org/img/books/1098127463s.jpg')
INSERT INTO book (id, title, subtitle, authors, image) VALUES (2, 'Financing Investment in Times of High Public Debt', '2023 European Public Investment Outlook', 'Floriana Cerniglia, Francesco Saraceno, Andrew Watt', 'https://www.dbooks.org/img/books/1805112015s.jpg')
INSERT INTO book (id, title, subtitle, authors, image) VALUES (3, 'ASP.NET Core 6 Succinctly', 'ASP.NET Core 6 Succinctly', 'Dirk Strauss', 'https://www.dbooks.org/img/books/164200233Xs.jpg')
INSERT INTO book (id, title, subtitle, authors, image) VALUES (4, 'Engineering Systems Dynamics, Modelling, Simulation, and Design', 'Lagrangian and Bond Graph Methods', 'Mehrzad Tabatabaian', 'https://www.dbooks.org/img/books/199013209Xs.jpg')
INSERT INTO book (id, title, subtitle, authors, image) VALUES (5, 'Build a Raspberry Pi Media Player', 'Power up your TV and music system', 'PJ Evans', 'https://www.dbooks.org/img/books/5709901124s.jpg')
-- -- INSERT INTO book (id, title, subtitle, authors, image) VALUES (4, '', '', '', '')
